send_magic_packet:
  name: Send Magic Packet (WOL)
  description: >
    Wake up a device in the same local network as the UPS by sending a WOL magic packet.
  fields:
    mac_address:
      name: Device MAC Address
      description: >
        MAC address of the target device, for example: 11:22:33:44:55:66.
      required: true
      selector:
        text: